# **************************************************************************
# *
# * Authors:     Laura Pérez Liens (laura.perez@cnb.csic.es)
# *
# * Unidad de Bioinformatica of Centro Nacional de Biotecnologia, CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307 USA
# *
# * All comments concerning this program package may be sent to the
# * e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os
import gzip

from pwem.protocols import EMProtocol
from pyworkflow.protocol.params import BooleanParam, PointerParam, IntParam

from pwchem import Plugin
from pwchem.constants import OPENBABEL_DIC
from pwchem.objects import FastqFile


class ProtFastpFilter(EMProtocol):
    """
    Filter FASTQ files using fastp.

    This protocol applies read filtering and quality control to FASTQ datasets
    using fastp. It accepts a FastqFile object as input and generates a new
    filtered FastqFile object suitable for downstream analysis.

    The output FASTQ metadata, including the number of reads and the mean read
    length, are calculated from the filtered FASTQ file(s) generated by fastp.
    Input metadata are used only for validation and to propagate sample
    information.

    Optionally, FastQC can be executed on the filtered reads to assess sequence
    quality after filtering. Reports generated by fastp and FastQC are stored
    within the output FastqFile object and can be visualized through the
    corresponding viewers.

    ----------------------------
    Input parameters
    ----------------------------

    inputFastq : FastqFile
        Input FASTQ dataset to be filtered.

    runFastqc : bool
        If True, FastQC is executed on the filtered FASTQ files.

    lengthRequired : int
        Minimum read length required after filtering.

    threads : int
        Number of worker threads used by fastp.

    qualifiedQualityPhred : int
        Minimum base quality considered qualified.

    unqualifiedPercentLimit : int
        Maximum percentage of unqualified bases allowed per read.

    nBaseLimit : int
        Maximum number of N bases allowed per read.

    averageQual : int
        Minimum average read quality.

    disableAdapterTrimming : bool
        If True, adapter trimming is disabled.

    ----------------------------
    Output
    ----------------------------

    outputFastq : FastqFile
        Filtered FASTQ dataset.

        The output object contains:

        - Filtered FASTQ file path(s).
        - Sample name.
        - Sequencing type.
        - Number of reads after filtering.
        - Mean read length after filtering.
        - fastp HTML report.
        - fastp JSON report.
        - FastQC HTML report, if generated.
        - FastQC HTML reports for read 1 and read 2, if paired-end.

    ----------------------------
    Notes
    ----------------------------

    - fastp and FastQC must be installed through the plugin binaries.
    - Filtered reads are written in FASTQ format.
    - Output FASTQ files are named using the sample name.
    - FastQC is executed on the filtered reads, not on the original input.
    - All fastp filtering parameters are configurable through the protocol form.
    - Filtering parameters are validated against the input read length when available.
    - Generated reports are stored as attributes of the output FastqFile object.
    """
    _label = 'fastp filter'

    def _defineParams(self, form):
        form.addSection(label='Input')

        form.addParam('inputFastq', PointerParam,
                      pointerClass='FastqFile',
                      label='Input FASTQ: ',
                      help='Input FASTQ dataset to be filtered.')

        form.addParam('runFastqc', BooleanParam,
                      default=False,
                      label='Run FastQC: ',
                      help='Execute FastQC on the filtered FASTQ files.')

        form.addSection(label='Fastp parameters')

        form.addParam('lengthRequired', IntParam,
                      default=15,
                      label='Minimum read length: ',
                      help='Reads shorter than this value will be discarded. '
                           'Corresponds to fastp option -l / --length_required.')

        form.addParam('threads', IntParam,
                      default=4,
                      label='Threads: ',
                      help='Number of worker threads. '
                           'Corresponds to fastp option -w / --thread.')

        form.addParam('qualifiedQualityPhred', IntParam,
                      default=15,
                      label='Qualified quality phred: ',
                      help='Minimum base quality considered qualified. '
                           'Corresponds to fastp option -q / --qualified_quality_phred.')

        form.addParam('unqualifiedPercentLimit', IntParam,
                      default=40,
                      label='Unqualified percent limit: ',
                      help='Maximum percentage of unqualified bases allowed per read. '
                           'Corresponds to fastp option -u / --unqualified_percent_limit.')

        form.addParam('nBaseLimit', IntParam,
                      default=10,
                      label='N base limit: ',
                      help='Reads with more N bases than this value will be discarded. '
                           'Corresponds to fastp option -n / --n_base_limit.')

        form.addParam('averageQual', IntParam,
                      default=0,
                      label='Average quality: ',
                      help='Reads with average quality below this value will be discarded. '
                           'Corresponds to fastp option -e / --average_qual.')

        form.addParam('disableAdapterTrimming', BooleanParam,
                      default=False,
                      label='Disable adapter trimming: ',
                      help='Disable fastp adapter trimming. '
                           'Corresponds to fastp option -A / --disable_adapter_trimming.')

    def _insertAllSteps(self):
        self._insertFunctionStep(self.filterStep)

    def filterStep(self):
        inputFastq = self.inputFastq.get()

        outputFastq = self._runFastp(inputFastq)

        if self.runFastqc.get():
            htmlFiles = self._runFastqc(outputFastq)

            if outputFastq.isPaired():
                if len(htmlFiles) < 2:
                    raise RuntimeError(
                        'Expected two FastQC HTML reports for paired-end data.'
                    )

                outputFastq.setFastqcHtmlR1(htmlFiles[0])
                outputFastq.setFastqcHtmlR2(htmlFiles[1])
            else:
                outputFastq.setFastqcHtml(htmlFiles[0])

        self._defineOutputs(outputFastq=outputFastq)

    def _runFastp(self, inputFastq):
        fn1 = inputFastq.getFileName()
        isPaired = inputFastq.isPaired()

        lengthRequired = self.lengthRequired.get()
        threads = self.threads.get()
        qualifiedQualityPhred = self.qualifiedQualityPhred.get()
        unqualifiedPercentLimit = self.unqualifiedPercentLimit.get()
        nBaseLimit = self.nBaseLimit.get()
        averageQual = self.averageQual.get()
        extraArgs = ''

        if self.disableAdapterTrimming.get():
            extraArgs += '-A '

        outDir = self._getExtraPath('fastp')
        os.makedirs(outDir, exist_ok=True)

        sampleName = inputFastq.getSampleName()

        if not sampleName:
            sampleName = 'sample'

        out1 = os.path.join(
            outDir,
            f'{sampleName}_filtered_R1.fastq'
        )

        reportHtml = os.path.join(
            outDir,
            f'{sampleName}_fastp.html'
        )

        reportJson = os.path.join(
            outDir,
            f'{sampleName}_fastp.json'
        )

        arguments = (
            f'-i "{fn1}" '
            f'-o "{out1}" '
            f'-w {threads} '
            f'-l {lengthRequired} '
            f'-q {qualifiedQualityPhred} '
            f'-u {unqualifiedPercentLimit} '
            f'-n {nBaseLimit} '
            f'-e {averageQual} '
            f'{extraArgs}'
            f'-h "{reportHtml}" '
            f'-j "{reportJson}"'
        )

        if isPaired:
            fn2 = inputFastq.getFileName2()

            out2 = os.path.join(
                outDir,
                f'{sampleName}_filtered_R2.fastq'
            )

            arguments = (
                f'-i "{fn1}" '
                f'-I "{fn2}" '
                f'-o "{out1}" '
                f'-O "{out2}" '
                f'-w {threads} '
                f'-l {lengthRequired} '
                f'-q {qualifiedQualityPhred} '
                f'-u {unqualifiedPercentLimit} '
                f'-n {nBaseLimit} '
                f'-e {averageQual} '
                f'{extraArgs}'
                f'-h "{reportHtml}" '
                f'-j "{reportJson}"'
            )

        Plugin.runCondaCommand(self, arguments, OPENBABEL_DIC, 'fastp')

        numReads, readLength = self._getFastqStats(out1)

        if isPaired:
            numReads2, readLength2 = self._getFastqStats(out2)

            if numReads != numReads2:
                raise RuntimeError(
                    'Filtered paired FASTQ files have different number of reads: '
                    'R1={} R2={}'.format(numReads, numReads2)
                )

            readLength = int(round((readLength + readLength2) / 2))

        outputFastq = FastqFile()
        outputFastq.setFileName(out1)
        outputFastq.setIsPaired(isPaired)
        outputFastq.setIsCompressed(False)
        outputFastq.setFormat('FASTQ')
        outputFastq.setHasQuality(True)
        outputFastq.setReadLength(readLength)
        outputFastq.setNumReads(numReads)

        sample = inputFastq.getSampleName()
        if sample:
            outputFastq.setSampleName(sample)

        if isPaired:
            outputFastq.setFileName2(out2)

        outputFastq.setFastpHtml(reportHtml)
        outputFastq.setFastpJson(reportJson)

        return outputFastq

    def _openFastq(self, fn):
        if fn.endswith('.gz'):
            return gzip.open(fn, 'rt')

        return open(fn, 'r')

    def _getFastqStats(self, fn):
        numReads = 0
        totalLength = 0

        with self._openFastq(fn) as f:
            while True:
                header = f.readline()

                if not header:
                    break

                seq = f.readline().strip()
                f.readline()
                f.readline()

                numReads += 1
                totalLength += len(seq)

        readLength = int(round(totalLength / numReads)) if numReads else 0

        return numReads, readLength

    def _runFastqc(self, outputFastq):
        if not outputFastq.supportsFastQC():
            raise RuntimeError(
                'FastQC cannot be executed because the input file does not '
                'contain quality scores.'
            )

        fn1 = outputFastq.getFileName()

        outDir = self._getExtraPath('fastqc')
        os.makedirs(outDir, exist_ok=True)

        arguments = f'-o "{outDir}" "{fn1}"'

        if outputFastq.isPaired():
            fn2 = outputFastq.getFileName2()
            arguments += f' "{fn2}"'

        Plugin.runCondaCommand(self, arguments, OPENBABEL_DIC, 'fastqc')

        htmlFiles = self._getFastqcHtmlFiles(outDir)

        if not htmlFiles:
            raise RuntimeError(
                'FastQC finished but no HTML report was generated.'
            )

        return htmlFiles

    def _getFastqcHtmlFiles(self, outDir):
        return sorted([
            os.path.join(outDir, f)
            for f in os.listdir(outDir)
            if f.endswith('.html')
        ])

    def _validate(self):
        errors = []

        inputFastq = self.inputFastq.get()
        if inputFastq is None:
            errors.append('An input FASTQ object is required.')
            return errors

        if inputFastq.isPaired() and not inputFastq.hasFileName2():
            errors.append(
                'Input FASTQ is marked as paired-end but read 2 is missing.'
            )

        if not inputFastq.hasQuality():
            errors.append(
                'Input file does not contain quality scores and cannot be '
                'processed as FASTQ.'
            )

        if self.lengthRequired.get() < 0:
            errors.append('Minimum read length must be greater than or equal to 0.')

        if inputFastq.getReadLength() > 0:
            if self.lengthRequired.get() > inputFastq.getReadLength():
                errors.append(
                    f'Minimum read length ({self.lengthRequired.get()}) is larger '
                    f'than the input read length ({inputFastq.getReadLength()}).'
                )

        if self.threads.get() < 1:
            errors.append('Threads must be greater than or equal to 1.')

        if not 0 <= self.qualifiedQualityPhred.get() <= 36:
            errors.append('Qualified quality phred must be between 0 and 36.')

        if not 0 <= self.unqualifiedPercentLimit.get() <= 100:
            errors.append('Unqualified percent limit must be between 0 and 100.')

        if self.nBaseLimit.get() < 0:
            errors.append('N base limit must be greater than or equal to 0.')

        if self.averageQual.get() < 0:
            errors.append('Average quality must be greater than or equal to 0.')

        return errors

    def _summary(self):
        summary = []

        inputFastq = self.inputFastq.get()

        summary.append('FASTQ filtering performed with fastp')
        summary.append(f'Minimum read length: {self.lengthRequired.get()}')
        summary.append(f'Threads: {self.threads.get()}')
        summary.append(f'Qualified quality phred: {self.qualifiedQualityPhred.get()}')
        summary.append(f'Unqualified percent limit: {self.unqualifiedPercentLimit.get()}')
        summary.append(f'N base limit: {self.nBaseLimit.get()}')
        summary.append(f'Average quality: {self.averageQual.get()}')
        summary.append(
            f'Adapter trimming: '
            f'{"disabled" if self.disableAdapterTrimming.get() else "enabled"}'
        )

        if inputFastq:
            summary.append(f'Input: {inputFastq.getFileName()}')
            if inputFastq.getReadLength() > 0:
                summary.append(
                    f'Input read length: {inputFastq.getReadLength()} bp'
                )
            if inputFastq.getNumReads() > 0:
                summary.append(
                    f'Input number of reads: {inputFastq.getNumReads()}'
                )
            summary.append(
                f'Sequencing type: '
                f'{"paired-end" if inputFastq.isPaired() else "single-end"}'
            )

        if hasattr(self, 'outputFastq'):
            outputFastq = self.outputFastq

            if outputFastq.getReadLength() > 0:
                summary.append(
                    f'Output read length: {outputFastq.getReadLength()} bp'
                )

            if outputFastq.getNumReads() > 0:
                summary.append(
                    f'Output number of reads: {outputFastq.getNumReads()}'
                )

        summary.append(
            f'FastQC: {"executed" if self.runFastqc.get() else "not executed"}'
        )

        return summary

    def _methods(self):
        methods = []

        methods.append(
            'Reads were filtered using fastp with the following parameters: '
            f'minimum read length {self.lengthRequired.get()} bp, '
            f'{self.threads.get()} threads, '
            f'qualified quality phred {self.qualifiedQualityPhred.get()}, '
            f'unqualified percent limit {self.unqualifiedPercentLimit.get()}%, '
            f'N base limit {self.nBaseLimit.get()}, '
            f'minimum average quality {self.averageQual.get()}, '
            f'and adapter trimming '
            f'{"disabled" if self.disableAdapterTrimming.get() else "enabled"}.'
        )

        if hasattr(self, 'outputFastq'):
            outputFastq = self.outputFastq

            methods.append(
                f'The filtered FASTQ dataset contains '
                f'{outputFastq.getNumReads()} reads with an average read '
                f'length of {outputFastq.getReadLength()} bp.'
            )

        if self.runFastqc.get():
            methods.append(
                'FastQC quality control was performed on the filtered FASTQ files.'
            )

        return methods