# **************************************************************************
# *
# * Authors:     Laura Pérez Liens (laura.perez@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import json
import os
import re
import shlex
import shutil

from pyworkflow.protocol.params import BooleanParam,EnumParam,IntParam,PathParam,PointerParam,StringParam
from pwem.protocols import EMProtocol

from pwchem import Plugin
from pwchem.constants import RNASEQ_DIC
from pwchem.objects import AlignmentFile


class ProtRNASeqAlignment(EMProtocol):
    """
    Align RNA-seq reads against a reference genome using STAR or HISAT2.

    This protocol performs the main alignment step of an RNA-seq workflow.
    It accepts a FastqFile object containing either single-end or paired-end
    sequencing reads and aligns them against a selected reference genome using
    STAR or HISAT2.

    The protocol automatically builds the genome index required by the selected
    aligner, performs the alignment, sorts the resulting alignments by genomic
    coordinate, creates a BAM index and extracts basic mapping statistics. The
    final result is stored as an AlignmentFile object that can be used by
    downstream Scipion protocols.

    ----------------------------
    Input reads
    ----------------------------

    inputFastq : FastqFile
        Input RNA-seq reads represented as a Scipion FastqFile object.

        Both single-end and paired-end datasets are supported. The sequencing
        type is obtained directly from the FastqFile object, so it does not need
        to be specified again in this protocol.

        For paired-end datasets, both read files stored in the FastqFile object
        are passed to the selected aligner.

    ----------------------------
    Reference genome
    ----------------------------

    The reference genome can be provided in two different ways:

    1. SetOfGenomes object

       A SetOfGenomes generated by ProtReferenceGenomes or another compatible
       Scipion protocol can be used directly.

       If the set contains more than one Genome object, the genomeIndex parameter
       determines which genome is used for the alignment.

       The selected Genome object may provide:

       - Reference genome FASTA file.
       - GTF annotation file.
       - Scientific name.
       - Genome assembly.
       - Genome release or accession.
       - Reference source, such as Ensembl or NCBI.

       The FASTA file is required. The GTF annotation is optional.

    2. Local reference files

       Alternatively, a local FASTA file can be supplied manually together with
       an optional GTF annotation file.

       A descriptive reference name and source can also be specified and will be
       stored in the output AlignmentFile metadata.

    ----------------------------
    Alignment programs
    ----------------------------

    Two RNA-seq aligners are supported:

    STAR
        STAR is a splice-aware aligner designed for RNA-seq data.

        Before alignment, a STAR genome index is generated from the selected
        reference FASTA file. If a GTF annotation is available, it is included
        during index generation to provide known splice-junction information.

        The sjdbOverhang parameter can be specified manually. When set to 0,
        the protocol automatically uses:

            read length - 1

        based on the mean read length stored in the input FastqFile object.

        STAR two-pass mode can optionally be enabled. In this mode, splice
        junctions detected during the first alignment pass are used during the
        second pass to improve splice-aware alignment.

    HISAT2
        HISAT2 is a splice-aware alignment program based on a hierarchical
        indexing strategy.

        A HISAT2 index is generated from the reference FASTA file before
        alignment.

        The --dta option can optionally be enabled to generate alignments
        suitable for downstream transcriptome reconstruction and assembly.

        Library strandness is passed to HISAT2 when requested. STAR does not use
        this parameter during alignment.

    ----------------------------
    Genome indexing
    ----------------------------

    A genome index is automatically generated according to the selected aligner:

    - STAR creates a STAR genome index directory.
    - HISAT2 creates the corresponding HISAT2 index files.

    The number of threads selected in the protocol is used during both genome
    index generation and read alignment.

    By default, genome index files are removed after successful execution to
    reduce disk usage. They can be preserved by enabling the
    keepIntermediateFiles option.

    ----------------------------
    Alignment output
    ----------------------------

    Both aligners ultimately produce a coordinate-sorted BAM file.

    For STAR, coordinate sorting is requested directly during alignment.

    For HISAT2, the SAM output generated by HISAT2 is piped directly to
    samtools sort to create a coordinate-sorted BAM file without keeping an
    intermediate SAM file.

    After alignment, samtools index is used to generate the corresponding
    BAI index.

    The protocol verifies that the BAM file exists and is not empty before
    creating the final output object.

    ----------------------------
    Alignment statistics
    ----------------------------

    Basic alignment statistics are extracted from the reports generated by
    STAR or HISAT2.

    The reported statistics include:

    - Total reads.
    - Mapped reads.
    - Uniquely mapped reads.
    - Multi-mapped reads.
    - Unmapped reads.
    - Overall mapping rate.
    - Unique mapping rate.
    - Multi-mapping rate.
    - Unmapped rate.

    STAR statistics are obtained from the STAR final log file.

    HISAT2 statistics are extracted from the alignment summary written to
    standard error.

    In addition, samtools flagstat is also executed on the final BAM file to provide
    additional alignment-level information. For single-end datasets, it may
    be used as a fallback when total or mapped read counts cannot be obtained
    from the aligner-specific report.

    ----------------------------
    Output
    ----------------------------

    outputAlignment : AlignmentFile
        Coordinate-sorted and indexed RNA-seq alignment.

        The output AlignmentFile stores:

        - BAM file path.
        - BAI index path.
        - Alignment format.
        - Sample name.
        - Aligner used.
        - Reference FASTA file.
        - Reference GTF file, when available.
        - Reference name.
        - Reference source.
        - Alignment command.
        - Aligner log file.
        - Sorting and indexing status.
        - Mapping statistics.

        Source relations are established between the AlignmentFile and the
        input FastqFile. When a SetOfGenomes is used as the reference source,
        a source relation with the input genome set is also created.

    ----------------------------
    Validation
    ----------------------------

    Before execution, the protocol validates that:

    - An input FastqFile object has been provided.
    - FASTQ files exist on disk.
    - Paired-end datasets contain both read files.
    - A valid reference genome has been selected.
    - The reference FASTA file exists.
    - The optional GTF file exists when provided.
    - The selected genome index is valid when using a SetOfGenomes.
    - STAR sjdbOverhang is either 0 or a positive integer.

    Execution is stopped if any required input file or reference information
    is missing.

    ----------------------------
    Notes
    ----------------------------

    - STAR, HISAT2 and samtools must be available in the RNA-seq software
      environment configured by the plugin.
    - FASTQ compression is detected from the input FastqFile object. STAR uses
      zcat automatically for compressed input files.
    - The reference GTF file is optional. STAR can use it during genome index
      generation when available.
    - Genome indexes can require substantial disk space, particularly for large
      eukaryotic genomes.
    - Intermediate genome indexes are removed by default after successful
      execution.
    - The resulting AlignmentFile is intended to serve as the input for
      downstream RNA-seq analysis protocols in Scipion.
    """

    # -------------------------------------------------------
    # Aligner choices
    # -------------------------------------------------------

    ALIGN_STAR = 0
    ALIGN_HISAT2 = 1
    ALIGNER_CONDITION = 'aligner == %d'

    # -------------------------------------------------------
    # Reference input choices
    # -------------------------------------------------------

    REFERENCE_FROM_OBJECT = 0
    REFERENCE_FROM_FILES = 1
    REFERENCE_SOURCE_CONDITION = 'referenceSource == %d'

    _label = 'RNA-seq alignment'

    # -------------------------------------------------------
    # Parameters
    # -------------------------------------------------------

    def _defineParams(self, form):
        form.addSection(label='Input reads')

        form.addParam(
            'inputFastq',
            PointerParam,
            pointerClass='FastqFile',
            label='Input FASTQ: ',
            help=(
                'Input FastqFile object. Single-end and paired-end inputs '
                'are detected automatically from the object.'
            )
        )

        form.addSection(label='Reference genome')

        form.addParam(
            'referenceSource',
            EnumParam,
            choices=[
                'Genome object',
                'Local FASTA/GTF files'
            ],
            default=self.REFERENCE_FROM_OBJECT,
            label='Reference source: ',
            help=(
                'Use a SetOfGenomes object produced by ProtReferenceGenomes or '
                'provide local reference files manually.'
            )
        )

        form.addParam(
            'inputGenomes',
            PointerParam,
            pointerClass='SetOfGenomes',
            label='Reference genomes: ',
            condition=self.REFERENCE_SOURCE_CONDITION % self.REFERENCE_FROM_OBJECT,
            help=(
                'Set of reference genomes produced by the '
                'Reference genomes protocol.'
            )
        )

        form.addParam(
            'genomeIndex',
            IntParam,
            default=0,
            condition=self.REFERENCE_SOURCE_CONDITION % self.REFERENCE_FROM_OBJECT,
            label='Genome: ',
            help='Select the reference genome using the wizard.'
        )

        form.addParam(
            'manualFasta',
            PathParam,
            label='Reference FASTA: ',
            condition=self.REFERENCE_SOURCE_CONDITION % self.REFERENCE_FROM_FILES,
            help='Local reference genome in FASTA format.'
        )

        form.addParam(
            'manualGtf',
            PathParam,
            allowsNull=True,
            label='Reference GTF: ',
            condition=self.REFERENCE_SOURCE_CONDITION % self.REFERENCE_FROM_FILES,
            help='Optional GTF annotation matching the reference FASTA.'
        )

        form.addParam(
            'manualReferenceName',
            StringParam,
            default='Custom reference',
            label='Reference name: ',
            condition=self.REFERENCE_SOURCE_CONDITION % self.REFERENCE_FROM_FILES,
            help='Descriptive name stored in the output AlignmentFile.'
        )

        form.addParam(
            'manualReferenceSource',
            StringParam,
            default='Local files',
            label='Reference source name: ',
            condition=self.REFERENCE_SOURCE_CONDITION % self.REFERENCE_FROM_FILES,
            help='Example: Ensembl, GENCODE, RefSeq, UCSC or Local files.'
        )

        form.addSection(label='Alignment options')

        form.addParam(
            'aligner',
            EnumParam,
            choices=['STAR', 'HISAT2'],
            default=self.ALIGN_STAR,
            label='Aligner: '
        )

        form.addParam(
            'starTwoPass',
            BooleanParam,
            default=True,
            label='STAR two-pass mode: ',
            condition=self.ALIGNER_CONDITION % self.ALIGN_STAR,
            help=(
                'Run STAR in Basic two-pass mode to improve splice-junction '
                'detection.'
            )
        )

        form.addParam(
            'starSjdbOverhang',
            IntParam,
            default=0,
            label='STAR sjdbOverhang: ',
            condition=self.ALIGNER_CONDITION % self.ALIGN_STAR,
            help=(
                'Use 0 to infer readLength - 1 from the FastqFile object. '
                'Otherwise provide a positive value.'
            )
        )

        form.addParam(
            'hisat2Dta',
            BooleanParam,
            default=True,
            label='HISAT2 downstream transcriptome mode: ',
            condition=self.ALIGNER_CONDITION % self.ALIGN_HISAT2,
            help='Enable --dta for downstream transcript assembly.'
        )

        form.addParam(
            'rnaStrandness',
            EnumParam,
            choices=[
                'Unstranded',
                'Forward',
                'Reverse'
            ],
            default=0,
            label='RNA strandness: ',
            help=(
                'Library strandness. For HISAT2, Forward is translated to F '
                'for single-end data and FR for paired-end data; Reverse is '
                'translated to R for single-end data and RF for paired-end data. '
                'STAR does not require this option for alignment.'
            )
        )

        form.addParam(
            'keepIntermediateFiles',
            BooleanParam,
            default=False,
            label='Keep genome index: ',
            help=(
                'Keep the STAR or HISAT2 genome index after the alignment. '
                'Indexes can require several gigabytes.'
            )
        )

        form.addParallelSection(
            threads=4,
            mpi=1
        )

    # -------------------------------------------------------
    # Steps
    # -------------------------------------------------------

    def _insertAllSteps(self):
        self._insertFunctionStep(self.prepareReferenceStep)
        self._insertFunctionStep(self.buildIndexStep)
        self._insertFunctionStep(self.alignStep)
        self._insertFunctionStep(self.parseStatisticsStep)
        self._insertFunctionStep(self.createOutputStep)
        self._insertFunctionStep(self.cleanupStep)

    # -------------------------------------------------------
    # Reference preparation
    # -------------------------------------------------------

    def prepareReferenceStep(self):
        """Resolve and persist reference paths and metadata."""
        referenceInfo = self._getReferenceInfo()

        fastaFile = referenceInfo['fastaFile']
        gtfFile = referenceInfo.get('gtfFile')

        if not os.path.isfile(fastaFile):
            raise RuntimeError(
                'Reference FASTA does not exist: {}'.format(fastaFile)
            )

        if gtfFile and not os.path.isfile(gtfFile):
            raise RuntimeError(
                'Reference GTF does not exist: {}'.format(gtfFile)
            )

        self._writeJson(
            self._getReferenceInfoFile(),
            referenceInfo
        )

    def _getReferenceInfo(self):
        if (
            self.referenceSource.get()
            == self.REFERENCE_FROM_OBJECT
        ):
            return self._getReferenceFromGenomeObject()

        return self._getReferenceFromFiles()

    def _getSelectedGenome(self):
        genomeSet = self.inputGenomes.get()

        if genomeSet is None:
            raise RuntimeError('No SetOfGenomes selected.')

        if genomeSet.getSize() == 0:
            raise RuntimeError('The selected SetOfGenomes is empty.')

        index = self.genomeIndex.get()

        if index < 0 or index >= genomeSet.getSize():
            raise RuntimeError(
                'Genome index {} is out of range for a SetOfGenomes '
                'containing {} genome(s).'.format(
                    index,
                    genomeSet.getSize()
                )
            )

        for currentIndex, genome in enumerate(genomeSet):
            if currentIndex == index:
                return genome.clone()

        raise RuntimeError(
            'The selected Genome could not be retrieved.'
        )

    def _getReferenceFromGenomeObject(self):
        genome = self._getSelectedGenome()
        fastaFile = genome.getFastaFile()
        gtfFile = (
            genome.getGtfFile()
            if genome.hasGtfFile()
            else None
        )

        scientificName = (
            genome.getScientificName()
            if genome.hasScientificName()
            else ''
        )
        assembly = (
            genome.getAssembly()
            if genome.hasAssembly()
            else ''
        )
        release = (
            genome.getRelease()
            if genome.hasRelease()
            else ''
        )
        source = (
            genome.getSource()
            if genome.hasSource()
            else 'Genome object'
        )

        referenceParts = [
            value
            for value in (scientificName, assembly)
            if value
        ]
        referenceName = ' '.join(referenceParts)

        if release:
            if source == 'NCBI':
                referenceName += ' - accession {}'.format(release)
            else:
                referenceName += ' - release {}'.format(release)

        if not referenceName:
            referenceName = 'Genome reference'

        return {
            'fastaFile': os.path.abspath(fastaFile),
            'gtfFile': (
                os.path.abspath(gtfFile)
                if gtfFile
                else None
            ),
            'referenceName': referenceName,
            'referenceSource': source,
            'scientificName': scientificName,
            'assembly': assembly,
            'release': release
        }

    def _getReferenceFromFiles(self):
        fastaFile = (self.manualFasta.get() or '').strip()
        gtfFile = (self.manualGtf.get() or '').strip()
        referenceName = (self.manualReferenceName.get() or '').strip()
        referenceSource = (self.manualReferenceSource.get() or '').strip()

        return {
            'fastaFile': os.path.abspath(fastaFile),
            'gtfFile': (
                os.path.abspath(gtfFile)
                if gtfFile
                else None
            ),
            'referenceName': referenceName or 'Custom reference',
            'referenceSource': referenceSource or 'Local files',
            'scientificName': '',
            'assembly': '',
            'release': ''
        }

    # -------------------------------------------------------
    # Genome index
    # -------------------------------------------------------

    def buildIndexStep(self):
        referenceInfo = self._readJson(
            self._getReferenceInfoFile()
        )

        if self.aligner.get() == self.ALIGN_STAR:
            indexInfo = self._buildStarIndex(referenceInfo)
        else:
            indexInfo = self._buildHisat2Index(referenceInfo)

        self._writeJson(
            self._getIndexInfoFile(),
            indexInfo
        )

    def _buildStarIndex(self, referenceInfo):
        indexDir = self._getExtraPath('star_index')
        os.makedirs(indexDir, exist_ok=True)

        marker = os.path.join(
            indexDir,
            'genomeParameters.txt'
        )

        if not os.path.exists(marker):
            args = [
                '--runMode genomeGenerate',
                '--genomeDir {}'.format(
                    self._quote(indexDir)
                ),
                '--genomeFastaFiles {}'.format(
                    self._quote(referenceInfo['fastaFile'])
                ),
                '--runThreadN {}'.format(
                    self.numberOfThreads.get()
                )
            ]

            gtfFile = referenceInfo.get('gtfFile')
            if gtfFile:
                args.extend([
                    '--sjdbGTFfile {}'.format(
                        self._quote(gtfFile)
                    ),
                    '--sjdbOverhang {}'.format(
                        self._getStarSjdbOverhang()
                    )
                ])

            command = 'STAR {}'.format(' '.join(args))

            Plugin.runCondaCommand(
                self,
                ' '.join(args),
                RNASEQ_DIC,
                'STAR'
            )

            if not os.path.exists(marker):
                raise RuntimeError(
                    'STAR genome index was not created in: {}'
                    .format(indexDir)
                )
        else:
            command = 'Existing STAR index: {}'.format(indexDir)

        return {
            'aligner': 'STAR',
            'indexPath': indexDir,
            'indexDirectory': indexDir,
            'indexCommand': command
        }

    def _buildHisat2Index(self, referenceInfo):
        indexDir = self._getExtraPath('hisat2_index')
        os.makedirs(indexDir, exist_ok=True)

        indexPrefix = os.path.join(
            indexDir,
            'genome'
        )

        standardMarker = indexPrefix + '.1.ht2'
        largeMarker = indexPrefix + '.1.ht2l'

        if not (
            os.path.exists(standardMarker)
            or os.path.exists(largeMarker)
        ):
            args = '{} {} --threads {}'.format(
                self._quote(referenceInfo['fastaFile']),
                self._quote(indexPrefix),
                self.numberOfThreads.get()
            )
            command = 'hisat2-build {}'.format(args)

            Plugin.runCondaCommand(
                self,
                args,
                RNASEQ_DIC,
                'hisat2-build'
            )

            if not (
                os.path.exists(standardMarker)
                or os.path.exists(largeMarker)
            ):
                raise RuntimeError(
                    'HISAT2 genome index was not created with prefix: {}'
                    .format(indexPrefix)
                )
        else:
            command = 'Existing HISAT2 index: {}'.format(indexPrefix)

        return {
            'aligner': 'HISAT2',
            'indexPath': indexPrefix,
            'indexDirectory': indexDir,
            'indexCommand': command
        }

    def _getStarSjdbOverhang(self):
        userValue = self.starSjdbOverhang.get()

        if userValue > 0:
            return userValue

        fastqObj = self.inputFastq.get()
        readLength = fastqObj.getReadLength()

        if readLength and readLength > 1:
            return readLength - 1

        return 100

    # -------------------------------------------------------
    # Alignment
    # -------------------------------------------------------

    def alignStep(self):
        indexInfo = self._readJson(
            self._getIndexInfoFile()
        )

        if self.aligner.get() == self.ALIGN_STAR:
            alignmentInfo = self._alignWithStar(indexInfo)
        else:
            alignmentInfo = self._alignWithHisat2(indexInfo)

        self._writeJson(
            self._getAlignmentInfoFile(),
            alignmentInfo
        )

    def _alignWithStar(self, indexInfo):
        fastqObj = self.inputFastq.get()
        outputPrefix = self._getExtraPath('star_')

        readFiles = [
            self._quote(fastqObj.getFileName())
        ]

        if fastqObj.isPaired():
            readFiles.append(
                self._quote(fastqObj.getFileName2())
            )

        args = [
            '--genomeDir {}'.format(
                self._quote(indexInfo['indexPath'])
            ),
            '--readFilesIn {}'.format(
                ' '.join(readFiles)
            ),
            '--runThreadN {}'.format(
                self.numberOfThreads.get()
            ),
            '--outSAMtype BAM SortedByCoordinate',
            '--outFileNamePrefix {}'.format(
                self._quote(outputPrefix)
            )
        ]

        if fastqObj.isCompressed():
            args.append('--readFilesCommand zcat')

        if self.starTwoPass.get():
            args.append('--twopassMode Basic')

        command = 'STAR {}'.format(' '.join(args))

        Plugin.runCondaCommand(
            self,
            ' '.join(args),
            RNASEQ_DIC,
            'STAR'
        )

        bamFile = self._getExtraPath(
            'star_Aligned.sortedByCoord.out.bam'
        )
        logFile = self._getExtraPath(
            'star_Log.final.out'
        )
        baiFile = bamFile + '.bai'

        self._validateAlignmentFile(bamFile)

        Plugin.runCondaCommand(
            self,
            'index -@ {} {}'.format(
                self.numberOfThreads.get(),
                self._quote(bamFile)
            ),
            RNASEQ_DIC,
            'samtools'
        )

        if not os.path.exists(baiFile):
            raise RuntimeError(
                'BAM index was not created: {}'.format(baiFile)
            )

        return {
            'alignmentFile': bamFile,
            'alignmentFormat': 'BAM',
            'indexFile': baiFile,
            'logFile': logFile,
            'aligner': 'STAR',
            'command': command,
            'sorted': True,
            'indexed': True
        }

    def _alignWithHisat2(self, indexInfo):
        fastqObj = self.inputFastq.get()

        bamFile = self._getExtraPath(
            'hisat2_alignment.sorted.bam'
        )
        baiFile = bamFile + '.bai'
        logFile = self._getExtraPath(
            'hisat2_alignment.log'
        )

        threads = self.numberOfThreads.get()

        hisatArgs = [
            '-x {}'.format(
                self._quote(indexInfo['indexPath'])
            ),
            '-p {}'.format(threads)
        ]

        if self.hisat2Dta.get():
            hisatArgs.append('--dta')

        strandness = self._getHisat2Strandness()
        if strandness:
            hisatArgs.append(
                '--rna-strandness {}'.format(strandness)
            )

        if fastqObj.isPaired():
            hisatArgs.extend([
                '-1 {}'.format(
                    self._quote(fastqObj.getFileName())
                ),
                '-2 {}'.format(
                    self._quote(fastqObj.getFileName2())
                )
            ])
        else:
            hisatArgs.append(
                '-U {}'.format(
                    self._quote(fastqObj.getFileName())
                )
            )

        pipelineArgs = (
            '{hisat} 2> {log} | '
            'samtools sort -@ {threads} -o {bam}'
        ).format(
            hisat=' '.join(hisatArgs),
            log=self._quote(logFile),
            threads=threads,
            bam=self._quote(bamFile)
        )

        command = 'hisat2 {}'.format(pipelineArgs)

        Plugin.runCondaCommand(
            self,
            pipelineArgs,
            RNASEQ_DIC,
            'hisat2'
        )

        self._validateAlignmentFile(bamFile)

        Plugin.runCondaCommand(
            self,
            'index -@ {} {}'.format(
                threads,
                self._quote(bamFile)
            ),
            RNASEQ_DIC,
            'samtools'
        )

        if not os.path.exists(baiFile):
            raise RuntimeError(
                'BAM index was not created: {}'.format(baiFile)
            )

        return {
            'alignmentFile': bamFile,
            'alignmentFormat': 'BAM',
            'indexFile': baiFile,
            'logFile': logFile,
            'aligner': 'HISAT2',
            'command': command,
            'sorted': True,
            'indexed': True
        }

    def _getHisat2Strandness(self):
        selection = self.rnaStrandness.get()

        if selection == 0:
            return None

        fastqObj = self.inputFastq.get()

        if fastqObj.isPaired():
            return 'FR' if selection == 1 else 'RF'

        return 'F' if selection == 1 else 'R'

    def _validateAlignmentFile(self, bamFile):
        if not os.path.exists(bamFile):
            raise RuntimeError(
                'Alignment BAM was not created: {}'.format(bamFile)
            )

        if os.path.getsize(bamFile) == 0:
            raise RuntimeError(
                'Alignment BAM is empty: {}'.format(bamFile)
            )

    # -------------------------------------------------------
    # Statistics
    # -------------------------------------------------------

    def parseStatisticsStep(self):
        alignmentInfo = self._readJson(
            self._getAlignmentInfoFile()
        )

        if alignmentInfo['aligner'] == 'STAR':
            statistics = self._parseStarStatistics()
            bamFile = self._getExtraPath(
                'star_Aligned.sortedByCoord.out.bam'
            )
        else:
            statistics = self._parseHisat2Statistics()
            bamFile = self._getExtraPath(
                'hisat2_alignment.sorted.bam'
            )

        statistics = self._completeStatisticsWithSamtools(
            bamFile,
            statistics
        )

        alignmentInfo['statistics'] = statistics

        self._writeJson(
            self._getAlignmentInfoFile(),
            alignmentInfo
        )

    def _parseStarStatistics(self):
        values = self._parseKeyValueLog(
            separator='|'
        )

        totalReads = self._toInt(
            values.get('Number of input reads')
        )
        uniqueReads = self._toInt(
            values.get('Uniquely mapped reads number')
        )
        uniqueRate = self._toPercent(
            values.get('Uniquely mapped reads %')
        )
        multiReads = self._toInt(
            values.get('Number of reads mapped to multiple loci')
        )
        multiRate = self._toPercent(
            values.get('% of reads mapped to multiple loci')
        )
        tooManyReads = self._toInt(
            values.get('Number of reads mapped to too many loci')
        )
        tooManyRate = self._toPercent(
            values.get('% of reads mapped to too many loci')
        )

        multiReads += tooManyReads
        multiRate += tooManyRate

        mappedReads = uniqueReads + multiReads
        unmappedReads = max(0, totalReads - mappedReads)

        mappingRate = self._percentage(
            mappedReads,
            totalReads
        )
        unmappedRate = self._percentage(
            unmappedReads,
            totalReads
        )

        return {
            'totalReads': totalReads,
            'mappedReads': mappedReads,
            'uniquelyMappedReads': uniqueReads,
            'multiMappedReads': multiReads,
            'unmappedReads': unmappedReads,
            'mappingRate': mappingRate,
            'uniqueMappingRate': uniqueRate,
            'multiMappingRate': multiRate,
            'unmappedRate': unmappedRate
        }

    def _parseHisat2Statistics(self):
        logFile = self._getExtraPath(
            'hisat2_alignment.log'
        )

        if not os.path.exists(logFile):
            return self._emptyStatistics()

        with open(logFile) as inputFile:
            text = inputFile.read()

        totalReads = self._firstRegexInt(
            text,
            r'^\s*(\d+)\s+reads;'
        )
        if totalReads == 0:
            totalReads = self._firstRegexInt(
                text,
                r'^\s*(\d+)\s+\(.+\)\s+were paired;'
            )

        overallRate = self._firstRegexFloat(
            text,
            r'([\d.]+)%\s+overall alignment rate'
        )

        fastqObj = self.inputFastq.get()

        if fastqObj.isPaired():
            uniqueReads = self._firstRegexInt(
                text,
                r'^\s*(\d+)\s+\([\d.]+%\)\s+aligned concordantly exactly 1 time$'
            )

            multiReads = self._firstRegexInt(
                text,
                r'^\s*(\d+)\s+\([\d.]+%\)\s+aligned concordantly >1 times$'
            )

        else:
            uniqueReads = self._firstRegexInt(
                text,
                r'^\s*(\d+)\s+\([\d.]+%\)\s+aligned exactly 1 time$'
            )

            multiReads = self._firstRegexInt(
                text,
                r'^\s*(\d+)\s+\([\d.]+%\)\s+aligned >1 times$'
            )

        mappedReads = uniqueReads + multiReads
        unmappedReads = max(0, totalReads - mappedReads)

        if totalReads > 0 and mappedReads == 0 and overallRate > 0:
            mappedReads = int(
                round(totalReads * overallRate / 100.0)
            )
            unmappedReads = max(
                0,
                totalReads - mappedReads
            )

        return {
            'totalReads': totalReads,
            'mappedReads': mappedReads,
            'uniquelyMappedReads': uniqueReads,
            'multiMappedReads': multiReads,
            'unmappedReads': unmappedReads,
            'mappingRate': (
                overallRate
                if overallRate > 0
                else self._percentage(mappedReads, totalReads)
            ),
            'uniqueMappingRate': self._percentage(
                uniqueReads,
                totalReads
            ),
            'multiMappingRate': self._percentage(
                multiReads,
                totalReads
            ),
            'unmappedRate': self._percentage(
                unmappedReads,
                totalReads
            )
        }

    def _completeStatisticsWithSamtools(self, bamFile, statistics):
        """
        Use samtools flagstat as a fallback for total and mapped reads.

        STAR and HISAT2 count paired-end records differently in their logs,
        so the aligner log remains the primary source. flagstat is used only
        when a value could not be parsed.
        """
        flagstatFile = self._getExtraPath(
            'alignment_flagstat.txt'
        )

        Plugin.runCondaCommand(
            self,
            'flagstat -@ {} {} > {}'.format(
                self.numberOfThreads.get(),
                self._quote(bamFile),
                self._quote(flagstatFile)
            ),
            RNASEQ_DIC,
            'samtools'
        )

        if not os.path.exists(flagstatFile):
            return statistics

        with open(flagstatFile) as inputFile:
            text = inputFile.read()

        flagstatTotal = self._firstRegexInt(
            text,
            r'^(\d+)\s+\+\s+\d+\s+in total'
        )
        flagstatMapped = self._firstRegexInt(
            text,
            r'^(\d+)\s+\+\s+\d+\s+mapped\s+\('
        )

        fastqObj = self.inputFastq.get()

        if not fastqObj.isPaired():
            if statistics.get('totalReads', 0) == 0:
                statistics['totalReads'] = flagstatTotal

            if statistics.get('mappedReads', 0) == 0:
                statistics['mappedReads'] = flagstatMapped

        totalReads = statistics.get('totalReads', 0)
        mappedReads = statistics.get('mappedReads', 0)

        if statistics.get('unmappedReads', 0) == 0:
            statistics['unmappedReads'] = max(
                0,
                totalReads - mappedReads
            )

        if not statistics.get('mappingRate', 0.0):
            statistics['mappingRate'] = self._percentage(
                mappedReads,
                totalReads
            )

        if not statistics.get('unmappedRate', 0.0):
            statistics['unmappedRate'] = self._percentage(
                statistics['unmappedReads'],
                totalReads
            )

        return statistics

    def _parseKeyValueLog(self, separator='|'):
        values = {}

        logFile = self._getExtraPath(
            'star_Log.final.out'
        )

        if not os.path.exists(logFile):
            return values

        with open(logFile) as inputFile:
            for line in inputFile:
                if separator not in line:
                    continue

                key, value = line.split(separator, 1)
                values[key.strip()] = value.strip()

        return values

    @staticmethod
    def _emptyStatistics():
        return {
            'totalReads': 0,
            'mappedReads': 0,
            'uniquelyMappedReads': 0,
            'multiMappedReads': 0,
            'unmappedReads': 0,
            'mappingRate': 0.0,
            'uniqueMappingRate': 0.0,
            'multiMappingRate': 0.0,
            'unmappedRate': 0.0
        }

    @staticmethod
    def _toInt(value):
        if value is None:
            return 0

        cleaned = str(value).replace(',', '').strip()

        try:
            return int(cleaned)
        except ValueError:
            return 0

    @staticmethod
    def _toPercent(value):
        if value is None:
            return 0.0

        cleaned = str(value).replace('%', '').strip()

        try:
            return float(cleaned)
        except ValueError:
            return 0.0

    @staticmethod
    def _percentage(numerator, denominator):
        if not denominator:
            return 0.0

        return round(
            100.0 * float(numerator) / float(denominator),
            4
        )

    @staticmethod
    def _firstRegexInt(text, pattern):
        match = re.search(
            pattern,
            text,
            flags=re.MULTILINE
        )
        return int(match.group(1)) if match else 0

    @staticmethod
    def _firstRegexFloat(text, pattern):
        match = re.search(
            pattern,
            text,
            flags=re.MULTILINE
        )
        return float(match.group(1)) if match else 0.0

    @staticmethod
    def _sumRegexInts(text, patterns):
        total = 0

        for pattern in patterns:
            matches = re.findall(
                pattern,
                text,
                flags=re.MULTILINE
            )
            total += sum(int(value) for value in matches)

        return total

    # -------------------------------------------------------
    # Output
    # -------------------------------------------------------

    def createOutputStep(self):
        referenceInfo = self._readJson(
            self._getReferenceInfoFile()
        )
        alignmentInfo = self._readJson(
            self._getAlignmentInfoFile()
        )
        statistics = alignmentInfo.get(
            'statistics',
            self._emptyStatistics()
        )

        fastqObj = self.inputFastq.get()

        outputAlignment = AlignmentFile(
            filename=alignmentInfo['alignmentFile']
        )

        outputAlignment.setFormat(
            alignmentInfo['alignmentFormat']
        )
        outputAlignment.setSampleName(
            fastqObj.getSampleName()
        )
        outputAlignment.setAligner(
            alignmentInfo['aligner']
        )

        outputAlignment.setReferenceFasta(
            referenceInfo['fastaFile']
        )

        if referenceInfo.get('gtfFile'):
            outputAlignment.setReferenceGtf(
                referenceInfo['gtfFile']
            )

        outputAlignment.setReferenceName(
            referenceInfo['referenceName']
        )
        outputAlignment.setReferenceSource(
            referenceInfo['referenceSource']
        )

        outputAlignment.setIsSorted(
            alignmentInfo['sorted']
        )
        outputAlignment.setIsIndexed(
            alignmentInfo['indexed']
        )
        outputAlignment.setIndexFile(
            alignmentInfo['indexFile']
        )

        if alignmentInfo.get('logFile'):
            outputAlignment.setLogFile(
                alignmentInfo['logFile']
            )

        outputAlignment.setCommand(
            alignmentInfo['command']
        )

        outputAlignment.setTotalReads(
            statistics['totalReads']
        )
        outputAlignment.setMappedReads(
            statistics['mappedReads']
        )
        outputAlignment.setUniquelyMappedReads(
            statistics['uniquelyMappedReads']
        )
        outputAlignment.setMultiMappedReads(
            statistics['multiMappedReads']
        )
        outputAlignment.setUnmappedReads(
            statistics['unmappedReads']
        )
        outputAlignment.setMappingRate(
            statistics['mappingRate']
        )
        outputAlignment.setUniqueMappingRate(
            statistics['uniqueMappingRate']
        )
        outputAlignment.setMultiMappingRate(
            statistics['multiMappingRate']
        )
        outputAlignment.setUnmappedRate(
            statistics['unmappedRate']
        )

        self._defineOutputs(
            outputAlignment=outputAlignment
        )

        self._defineSourceRelation(
            self.inputFastq,
            outputAlignment
        )

        if (
            self.referenceSource.get()
            == self.REFERENCE_FROM_OBJECT
        ):
            self._defineSourceRelation(
                self.inputGenomes,
                outputAlignment
            )

    # -------------------------------------------------------
    # Cleanup
    # -------------------------------------------------------

    def cleanupStep(self):
        if self.keepIntermediateFiles.get():
            return

        indexInfo = self._readJson(
            self._getIndexInfoFile()
        )
        indexDirectory = indexInfo.get(
            'indexDirectory'
        )

        if (
            indexDirectory
            and os.path.isdir(indexDirectory)
        ):
            shutil.rmtree(indexDirectory)

    # -------------------------------------------------------
    # Persistent information
    # -------------------------------------------------------

    def _getReferenceInfoFile(self):
        return self._getExtraPath(
            'reference_info.json'
        )

    def _getIndexInfoFile(self):
        return self._getExtraPath(
            'index_info.json'
        )

    def _getAlignmentInfoFile(self):
        return self._getExtraPath(
            'alignment_info.json'
        )

    @staticmethod
    def _writeJson(filePath, data):
        with open(filePath, 'w') as outputFile:
            json.dump(
                data,
                outputFile,
                indent=2,
                sort_keys=True
            )

    @staticmethod
    def _readJson(filePath):
        with open(filePath) as inputFile:
            return json.load(inputFile)

    @staticmethod
    def _quote(value):
        return shlex.quote(str(value))

    # -------------------------------------------------------
    # Validation
    # -------------------------------------------------------

    def _validate(self):
        errors = []

        self._validateFastq(errors)
        self._validateReference(errors)
        self._validateAlignmentParameters(errors)

        return errors

    def _validateFastq(self, errors):
        fastqObj = self.inputFastq.get()

        if fastqObj is None:
            errors.append(
                'An input FastqFile object is required.'
            )
            return

        read1 = fastqObj.getFileName()

        if not read1:
            errors.append(
                'The input FASTQ read 1 path is empty.'
            )
        elif not os.path.isfile(read1):
            errors.append(
                'The input FASTQ read 1 file does not exist: {}'
                .format(read1)
            )

        if fastqObj.isPaired():
            read2 = fastqObj.getFileName2()

            if not read2:
                errors.append(
                    'Paired-end input requires a read 2 file.'
                )
            elif not os.path.isfile(read2):
                errors.append(
                    'The input FASTQ read 2 file does not exist: {}'
                    .format(read2)
                )

    def _validateReference(self, errors):
        if (
                self.referenceSource.get()
                == self.REFERENCE_FROM_OBJECT
        ):
            self._validateGenomeObjectReference(errors)
        else:
            self._validateLocalReference(errors)

    def _validateGenomeObjectReference(self, errors):
        try:
            genome = self._getSelectedGenome()
        except RuntimeError as error:
            errors.append(str(error))
            return

        fastaFile = genome.getFastaFile()

        if not fastaFile:
            errors.append(
                'The selected Genome does not contain a FASTA file.'
            )
        elif not os.path.isfile(fastaFile):
            errors.append(
                'The genome FASTA file does not exist: {}'
                .format(fastaFile)
            )

        if genome.hasGtfFile():
            gtfFile = genome.getGtfFile()

            if not os.path.isfile(gtfFile):
                errors.append(
                    'The genome GTF file does not exist: {}'
                    .format(gtfFile)
                )

    def _validateLocalReference(self, errors):
        fastaFile = (self.manualFasta.get() or '').strip()
        gtfFile = (self.manualGtf.get() or '').strip()

        if not fastaFile:
            errors.append(
                'A reference FASTA file is required.'
            )
        elif not os.path.isfile(fastaFile):
            errors.append(
                'The reference FASTA file does not exist: {}'
                .format(fastaFile)
            )

        if gtfFile and not os.path.isfile(gtfFile):
            errors.append(
                'The reference GTF file does not exist: {}'
                .format(gtfFile)
            )

    def _validateAlignmentParameters(self, errors):
        if (
            self.aligner.get() == self.ALIGN_STAR
            and self.starSjdbOverhang.get() < 0
        ):
            errors.append(
                'STAR sjdbOverhang must be 0 or a positive integer.'
            )

    # -------------------------------------------------------
    # Summary and methods
    # -------------------------------------------------------
    def _getAvailableGenomesSummary(self):
        summary = []

        genomeSet = self.inputGenomes.get()

        if genomeSet is None:
            return summary

        if genomeSet.getSize() == 0:
            return summary

        summary.append(
            'Available genomes:'
        )

        for i, genome in enumerate(genomeSet):
            summary.append(
                self._formatGenomeSummary(
                    i,
                    genome
                )
            )

        summary.extend([
            '',
            "Use the wizard next to 'Genome' to select "
            "the reference genome.",
            ''
        ])

        return summary

    @staticmethod
    def _formatGenomeSummary(index, genome):
        species = (
            genome.getScientificName()
            if genome.hasScientificName()
            else 'Unknown species'
        )

        assembly = (
            genome.getAssembly()
            if genome.hasAssembly()
            else ''
        )

        release = (
            genome.getRelease()
            if genome.hasRelease()
            else ''
        )

        source = (
            genome.getSource()
            if genome.hasSource()
            else ''
        )

        line = '{} -> {}'.format(
            index,
            species
        )

        if assembly:
            line += ' ({})'.format(
                assembly
            )

        if release:
            if source:
                line += ', {} {}'.format(
                    source,
                    release
                )
            else:
                line += ', release {}'.format(
                    release
                )

        return line

    def _summary(self):
        summary = []

        if self.referenceSource.get() == self.REFERENCE_FROM_OBJECT:
            summary.extend(
                self._getAvailableGenomesSummary()
            )

        if not hasattr(self, 'outputAlignment'):
            summary.append(
                'No alignment has been generated.'
            )
            return summary

        output = self.outputAlignment

        summary.extend([
            'Aligner: {}'.format(
                output.getAligner()
            ),
            'Reference: {}'.format(
                output.getReferenceName()
            ),
            'Reference source: {}'.format(
                output.getReferenceSource()
            ),
            'Output: {}'.format(
                output.getFileName()
            ),
            'Mapping rate: {:.2f}%'.format(
                output.getMappingRate()
            ),
            'Mapped reads: {}'.format(
                output.getMappedReads()
            ),
            'Unmapped reads: {}'.format(
                output.getUnmappedReads()
            )
        ])

        if output.hasReferenceGtf():
            summary.append(
                'Annotation: {}'.format(
                    output.getReferenceGtf()
                )
            )

        return summary

    def _methods(self):
        if not hasattr(self, 'outputAlignment'):
            return []

        output = self.outputAlignment

        return [
            (
                'RNA-seq reads from sample "{}" were aligned against "{}" '
                'using {}. The resulting alignment was coordinate-sorted '
                'and indexed as a BAM file. The observed mapping rate was '
                '{:.2f}%.'
            ).format(
                output.getSampleName() or 'unnamed',
                output.getReferenceName(),
                output.getAligner(),
                output.getMappingRate()
            )
        ]