# **************************************************************************
# *
# * Authors:    Laura Pérez Liens (laura.perez@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import os
import shlex

from pyworkflow.protocol.params import BooleanParam, PathParam, PointerParam
from pwem.protocols import EMProtocol

from pwchem import Plugin
from pwchem.constants import RNASEQ_DIC


class ProtGATK(EMProtocol):
    """
    Process RNA-seq BAM alignments using one or more GATK operations.

    Available operations
    --------------------

    SplitNCigarReads
        Splits RNA-seq reads containing N operators in their CIGAR strings.
        RNA-seq aligners such as STAR use the N operator to represent reads
        spanning splice junctions.

    BaseRecalibrator
        Analyses the BAM and known variant sites to build a base-quality
        recalibration model. This operation produces a recalibration table
        and requires a known-sites VCF, such as dbSNP.

    ApplyBQSR
        Applies the recalibration table generated by BaseRecalibrator to the
        BAM file and produces a recalibrated BAM.

    Execution order
    ---------------

    When several operations are selected they are always executed as:

        SplitNCigarReads
            -> BaseRecalibrator
            -> ApplyBQSR

    ApplyBQSR requires BaseRecalibrator to be selected in the same protocol
    execution.

    The reference FASTA is obtained automatically from the input
    AlignmentFile. Its FASTA index and GATK sequence dictionary are generated
    if necessary.

    Mutect2 is intentionally not included because it performs variant calling
    and produces VCF output rather than another AlignmentFile.
    """

    _label = 'GATK processing'

    # -------------------------------------------------------
    # Parameters
    # -------------------------------------------------------

    def _defineParams(self, form):
        form.addSection(label='Input')

        form.addParam(
            'inputAlignment',
            PointerParam,
            pointerClass='AlignmentFile',
            label='Input alignment: ',
            help=(
                'Input BAM represented as an AlignmentFile object. '
                'The reference FASTA associated with the alignment is '
                'obtained automatically from this object.'
            )
        )

        form.addSection(label='GATK operations')

        form.addParam(
            'splitNCigarReads',
            BooleanParam,
            default=True,
            label='Split reads with N in CIGAR: ',
            help=(
                'Run GATK SplitNCigarReads. RNA-seq aligners use the N '
                'CIGAR operator for reads spanning splice junctions. '
                'This operation splits those reads into exon-like segments '
                'and prepares the BAM for downstream GATK processing.'
            )
        )

        form.addParam(
            'baseRecalibrator',
            BooleanParam,
            default=True,
            label='Base recalibrator: ',
            help=(
                'Run GATK BaseRecalibrator. This operation analyses base '
                'quality scores and known variant sites to build a '
                'recalibration model. It produces a recalibration table '
                'that can later be applied with ApplyBQSR.'
            )
        )

        form.addParam(
            'knownSites',
            PathParam,
            label='Known-sites VCF: ',
            condition='baseRecalibrator',
            help=(
                'VCF containing known variants, such as dbSNP. '
                'This file is required by BaseRecalibrator so that known '
                'biological variants are not interpreted as sequencing errors.'
            )
        )

        form.addParam(
            'applyBQSR',
            BooleanParam,
            default=True,
            label='Apply base quality score recalibration (ApplyBQSR): ',
            help=(
                'Run GATK ApplyBQSR. This operation applies the recalibration '
                'table generated by BaseRecalibrator to the BAM and produces '
                'a recalibrated BAM file.'
            )
        )

        form.addParallelSection(
            threads=4,
            mpi=1
        )

    # -------------------------------------------------------
    # Steps
    # -------------------------------------------------------

    def _insertAllSteps(self):
        self._insertFunctionStep(self.prepareReferenceStep)

        if self.splitNCigarReads.get():
            self._insertFunctionStep(self.splitNCigarReadsStep)

        if self.baseRecalibrator.get():
            self._insertFunctionStep(self.baseRecalibratorStep)

        if self.applyBQSR.get():
            self._insertFunctionStep(self.applyBQSRStep)

        self._insertFunctionStep(self.indexFinalBamStep)
        self._insertFunctionStep(self.createOutputStep)

    # -------------------------------------------------------
    # Reference preparation
    # -------------------------------------------------------

    def prepareReferenceStep(self):
        alignment = self.inputAlignment.get()
        referenceFasta = self._getReferenceFasta(alignment)

        if not referenceFasta:
            raise RuntimeError(
                'GATK requires a reference FASTA stored in the '
                'input AlignmentFile.'
            )

        if not os.path.isfile(referenceFasta):
            raise RuntimeError(
                'Reference FASTA does not exist: {}'.format(referenceFasta)
            )

        self._ensureFastaIndex(referenceFasta)
        self._ensureSequenceDictionary(referenceFasta)

        if self.baseRecalibrator.get():
            knownSites = (self.knownSites.get() or '').strip()

            if not os.path.isfile(knownSites):
                raise RuntimeError(
                    'Known-sites VCF does not exist: {}'.format(knownSites)
                )

            self._ensureFeatureIndex(knownSites)

    # -------------------------------------------------------
    # GATK operations
    # -------------------------------------------------------

    def splitNCigarReadsStep(self):
        alignment = self.inputAlignment.get()
        inputBam = alignment.getFileName()
        referenceFasta = self._getReferenceFasta(alignment)
        outputBam = self._getSplitBam()

        self._validateBamFile(inputBam)

        args = (
            'SplitNCigarReads '
            '-R {reference} '
            '-I {inputBam} '
            '-O {outputBam}'
        ).format(
            reference=self._quote(referenceFasta),
            inputBam=self._quote(inputBam),
            outputBam=self._quote(outputBam)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        self._validateBamFile(outputBam)
        self._appendCommand('gatk {}'.format(args))

    def baseRecalibratorStep(self):
        alignment = self.inputAlignment.get()
        inputBam = self._getInputForBaseRecalibrator()
        referenceFasta = self._getReferenceFasta(alignment)
        knownSites = (self.knownSites.get() or '').strip()
        recalTable = self._getRecalibrationTable()

        self._validateBamFile(inputBam)

        args = (
            'BaseRecalibrator '
            '-R {reference} '
            '-I {inputBam} '
            '--known-sites {knownSites} '
            '-O {recalTable}'
        ).format(
            reference=self._quote(referenceFasta),
            inputBam=self._quote(inputBam),
            knownSites=self._quote(knownSites),
            recalTable=self._quote(recalTable)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        if not os.path.isfile(recalTable):
            raise RuntimeError(
                'BaseRecalibrator did not create the recalibration table: {}'
                .format(recalTable)
            )

        self._appendCommand('gatk {}'.format(args))

    def applyBQSRStep(self):
        alignment = self.inputAlignment.get()
        inputBam = self._getInputForApplyBQSR()
        referenceFasta = self._getReferenceFasta(alignment)
        recalTable = self._getRecalibrationTable()
        outputBam = self._getBqsrBam()

        self._validateBamFile(inputBam)

        if not os.path.isfile(recalTable):
            raise RuntimeError(
                'ApplyBQSR requires a recalibration table generated by '
                'BaseRecalibrator.'
            )

        args = (
            'ApplyBQSR '
            '-R {reference} '
            '-I {inputBam} '
            '--bqsr-recal-file {recalTable} '
            '-O {outputBam}'
        ).format(
            reference=self._quote(referenceFasta),
            inputBam=self._quote(inputBam),
            recalTable=self._quote(recalTable),
            outputBam=self._quote(outputBam)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        self._validateBamFile(outputBam)
        self._appendCommand('gatk {}'.format(args))

    # -------------------------------------------------------
    # Final BAM
    # -------------------------------------------------------

    def indexFinalBamStep(self):
        finalBam = self._getFinalBam()

        self._validateBamFile(finalBam)

        Plugin.runCondaCommand(
            self,
            'index -@ {} {}'.format(
                self.numberOfThreads.get(),
                self._quote(finalBam)
            ),
            RNASEQ_DIC,
            'samtools'
        )

        baiFile = finalBam + '.bai'

        if not os.path.isfile(baiFile):
            raise RuntimeError(
                'BAM index was not created: {}'.format(baiFile)
            )

    def createOutputStep(self):
        inputAlignment = self.inputAlignment.get()

        finalBam = self._getFinalBam()
        finalBai = finalBam + '.bai'

        outputAlignment = inputAlignment.clone()
        outputAlignment.setFileName(finalBam)
        outputAlignment.setIndexFile(finalBai)
        outputAlignment.setIsIndexed(True)

        if hasattr(outputAlignment, 'setIsSorted'):
            outputAlignment.setIsSorted(True)

        if hasattr(outputAlignment, 'setCommand'):
            outputAlignment.setCommand(self._readCommandHistory())

        self._defineOutputs(
            outputAlignment=outputAlignment
        )

        self._defineSourceRelation(
            self.inputAlignment,
            outputAlignment
        )

    # -------------------------------------------------------
    # BAM flow
    # -------------------------------------------------------

    def _getInputForBaseRecalibrator(self):
        if self.splitNCigarReads.get():
            return self._getSplitBam()

        return self.inputAlignment.get().getFileName()

    def _getInputForApplyBQSR(self):
        if self.splitNCigarReads.get():
            return self._getSplitBam()

        return self.inputAlignment.get().getFileName()

    def _getFinalBam(self):
        if self.applyBQSR.get():
            return self._getBqsrBam()

        if self.splitNCigarReads.get():
            return self._getSplitBam()

        return self.inputAlignment.get().getFileName()

    # -------------------------------------------------------
    # Paths
    # -------------------------------------------------------

    def _getSplitBam(self):
        return self._getExtraPath('split_n_cigar_reads.bam')

    def _getBqsrBam(self):
        return self._getExtraPath('bqsr.bam')

    def _getRecalibrationTable(self):
        return self._getExtraPath('recalibration.table')

    def _getCommandFile(self):
        return self._getExtraPath('gatk_commands.txt')

    # -------------------------------------------------------
    # Command history
    # -------------------------------------------------------

    def _appendCommand(self, command):
        with open(self._getCommandFile(), 'a') as outputFile:
            outputFile.write(command + '\n')

    def _readCommandHistory(self):
        commandFile = self._getCommandFile()

        if not os.path.isfile(commandFile):
            return ''

        with open(commandFile) as inputFile:
            commands = [
                line.strip()
                for line in inputFile
                if line.strip()
            ]

        return ' && '.join(commands)

    # -------------------------------------------------------
    # Reference helpers
    # -------------------------------------------------------

    def _ensureFastaIndex(self, referenceFasta):
        fastaIndex = referenceFasta + '.fai'

        if os.path.isfile(fastaIndex):
            return

        Plugin.runCondaCommand(
            self,
            'faidx {}'.format(self._quote(referenceFasta)),
            RNASEQ_DIC,
            'samtools'
        )

        if not os.path.isfile(fastaIndex):
            raise RuntimeError(
                'Reference FASTA index was not created: {}'.format(fastaIndex)
            )

    def _ensureSequenceDictionary(self, referenceFasta):
        dictionaryFile = self._getSequenceDictionaryPath(referenceFasta)

        if os.path.isfile(dictionaryFile):
            return

        args = (
            'CreateSequenceDictionary '
            '-R {reference} '
            '-O {dictionary}'
        ).format(
            reference=self._quote(referenceFasta),
            dictionary=self._quote(dictionaryFile)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        if not os.path.isfile(dictionaryFile):
            raise RuntimeError(
                'Reference sequence dictionary was not created: {}'
                .format(dictionaryFile)
            )

    def _ensureFeatureIndex(self, featureFile):
        possibleIndexes = [
            featureFile + '.idx',
            featureFile + '.tbi'
        ]

        if any(os.path.isfile(indexFile) for indexFile in possibleIndexes):
            return

        args = 'IndexFeatureFile -I {}'.format(
            self._quote(featureFile)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        if not any(os.path.isfile(indexFile) for indexFile in possibleIndexes):
            raise RuntimeError(
                'Known-sites VCF index was not created for: {}'
                .format(featureFile)
            )

    # -------------------------------------------------------
    # Alignment metadata
    # -------------------------------------------------------

    @staticmethod
    def _getReferenceFasta(alignment):
        if hasattr(alignment, 'getReferenceFasta'):
            return alignment.getReferenceFasta()

        return None

    @staticmethod
    def _getSequenceDictionaryPath(referenceFasta):
        root, extension = os.path.splitext(referenceFasta)

        if extension.lower() in ('.fa', '.fasta', '.fna'):
            return root + '.dict'

        return referenceFasta + '.dict'

    # -------------------------------------------------------
    # Validation helpers
    # -------------------------------------------------------

    @staticmethod
    def _validateBamFile(bamFile):
        if not bamFile:
            raise RuntimeError('The BAM path is empty.')

        if not os.path.isfile(bamFile):
            raise RuntimeError(
                'BAM file does not exist: {}'.format(bamFile)
            )

        if os.path.getsize(bamFile) == 0:
            raise RuntimeError(
                'BAM file is empty: {}'.format(bamFile)
            )

    @staticmethod
    def _quote(value):
        return shlex.quote(str(value))

    def _validate(self):
        errors = []
        alignment = self.inputAlignment.get()

        if alignment is None:
            errors.append(
                'An input AlignmentFile object is required.'
            )
            return errors

        bamFile = alignment.getFileName()

        if not bamFile:
            errors.append(
                'The input AlignmentFile does not contain a BAM path.'
            )
        elif not os.path.isfile(bamFile):
            errors.append(
                'The input BAM file does not exist: {}'.format(bamFile)
            )
        elif os.path.getsize(bamFile) == 0:
            errors.append(
                'The input BAM file is empty: {}'.format(bamFile)
            )

        if not (
            self.splitNCigarReads.get()
            or self.baseRecalibrator.get()
            or self.applyBQSR.get()
        ):
            errors.append(
                'Select at least one GATK operation.'
            )

        if self.applyBQSR.get() and not self.baseRecalibrator.get():
            errors.append(
                'ApplyBQSR requires BaseRecalibrator to be selected.'
            )

        referenceFasta = self._getReferenceFasta(alignment)

        if not referenceFasta:
            errors.append(
                'The input AlignmentFile does not contain a reference FASTA.'
            )
        elif not os.path.isfile(referenceFasta):
            errors.append(
                'The reference FASTA does not exist: {}'
                .format(referenceFasta)
            )

        if self.baseRecalibrator.get():
            knownSites = (self.knownSites.get() or '').strip()

            if not knownSites:
                errors.append(
                    'BaseRecalibrator requires a known-sites VCF.'
                )
            elif not os.path.isfile(knownSites):
                errors.append(
                    'The known-sites VCF does not exist: {}'
                    .format(knownSites)
                )

        return errors

    # -------------------------------------------------------
    # Summary and methods
    # -------------------------------------------------------

    def _getSelectedOperationNames(self):
        operations = []

        if self.splitNCigarReads.get():
            operations.append('SplitNCigarReads')

        if self.baseRecalibrator.get():
            operations.append('BaseRecalibrator')

        if self.applyBQSR.get():
            operations.append('ApplyBQSR')

        return operations

    def _summary(self):
        operations = ' -> '.join(
            self._getSelectedOperationNames()
        )

        if not hasattr(self, 'outputAlignment'):
            return [
                'Selected GATK operations: {}'.format(operations)
            ]

        summary = [
            'GATK operations: {}'.format(operations),
            'Output BAM: {}'.format(
                self.outputAlignment.getFileName()
            )
        ]

        if self.baseRecalibrator.get():
            summary.append(
                'Recalibration table: {}'.format(
                    self._getRecalibrationTable()
                )
            )

        return summary

    def _methods(self):
        if not hasattr(self, 'outputAlignment'):
            return []

        operations = ' followed by '.join(
            self._getSelectedOperationNames()
        )

        return [
            'The input RNA-seq BAM alignment was processed with GATK using '
            '{}. The resulting BAM file was indexed with samtools.'
            .format(operations)
        ]
