# **************************************************************************
# *
# * Authors:    Laura Pérez Liens (laura.perez@cnb.csic.es)
# *
# * Unidad de Bioinformatica of Centro Nacional de Biotecnologia, CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307 USA
# *
# * All comments concerning this program package may be sent to the
# * e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os
import shlex

from pyworkflow.protocol.params import (
    BooleanParam,
    IntParam,
    PointerParam
)
from pwem.protocols import EMProtocol

from pwchem import Plugin
from pwchem.constants import RNASEQ_DIC


class ProtGATK(EMProtocol):
    """
    Process RNA-seq BAM alignments using GATK.

    This protocol performs GATK preprocessing operations on RNA-seq BAM
    alignments. It is designed to prepare aligned RNA-seq reads for
    downstream variant analysis by processing spliced alignments and,
    optionally, performing base quality score recalibration (BQSR).

    The protocol accepts an ``AlignmentFile`` as input and obtains the
    associated reference genome FASTA automatically from the alignment
    metadata.

    The following GATK operations are supported:

    - SplitNCigarReads
    - BaseRecalibrator
    - ApplyBQSR

    When multiple operations are selected, they are executed sequentially
    in the appropriate order.


    ---------------------------------------------------------------------
    GATK operations
    ---------------------------------------------------------------------

    SplitNCigarReads
        Processes RNA-seq reads containing ``N`` operators in their CIGAR
        strings.

        RNA-seq aligners such as STAR use the ``N`` CIGAR operator to
        represent reads spanning introns. ``SplitNCigarReads`` splits these
        reads into exon-like segments suitable for downstream GATK
        processing.

    BaseRecalibrator
        Builds a base quality score recalibration model from the input BAM
        and a set of known variant sites.

        Known variants are provided through a ``SetOfVCFFiles``. A single
        ``VCFFile`` is selected from the set using the ``vcfIndex``
        parameter.

        The selected known-sites VCF is passed to GATK
        ``BaseRecalibrator`` using the ``--known-sites`` option.

        The operation generates a recalibration table that is subsequently
        used by ``ApplyBQSR``.

    ApplyBQSR
        Applies the recalibration model generated by ``BaseRecalibrator``
        to the BAM alignment.

        The operation produces a new BAM file containing the recalibrated
        base quality scores.

        ``ApplyBQSR`` requires ``BaseRecalibrator`` to be enabled in the
        same protocol execution.


    ---------------------------------------------------------------------
    Execution order
    ---------------------------------------------------------------------

    When all operations are enabled, they are executed in the following
    order::

        Input BAM
            |
            v
        SplitNCigarReads
            |
            v
        BaseRecalibrator
            |
            v
        ApplyBQSR
            |
            v
        Output BAM

    Operations that are not selected are skipped while preserving the
    required execution order.

    ``ApplyBQSR`` cannot be executed without ``BaseRecalibrator`` because
    it requires the recalibration table generated by that operation.


    ---------------------------------------------------------------------
    Reference genome
    ---------------------------------------------------------------------

    The reference genome FASTA is obtained automatically from the input
    ``AlignmentFile``.

    Before executing GATK, the protocol checks that the reference FASTA
    exists and prepares the auxiliary files required by GATK when
    necessary.

    These files include:

    FASTA index
        The ``.fai`` FASTA index is generated with samtools ``faidx`` when
        it does not already exist.

    Sequence dictionary
        The GATK/Picard sequence dictionary (``.dict``) is generated using
        GATK ``CreateSequenceDictionary`` when it does not already exist.

    Known-sites VCF index
        When ``BaseRecalibrator`` is enabled, the selected known-sites VCF
        must be indexed.

        Existing ``.idx``, ``.tbi`` and ``.csi`` indexes are accepted.

        If no compatible index is found, the protocol attempts to generate
        one using GATK ``IndexFeatureFile``.


    ---------------------------------------------------------------------
    Input parameters
    ---------------------------------------------------------------------

    inputAlignment : AlignmentFile
        Input RNA-seq BAM alignment.

        The object must contain:

        - A valid BAM file path.
        - The reference genome FASTA associated with the alignment.

        The reference FASTA is retrieved automatically from the
        ``AlignmentFile`` metadata.

    splitNCigarReads : bool
        If True, execute GATK ``SplitNCigarReads``.

        This operation processes RNA-seq reads containing ``N`` operators
        in their CIGAR strings and prepares spliced alignments for
        downstream GATK operations.

    baseRecalibrator : bool
        If True, execute GATK ``BaseRecalibrator``.

        A known-sites ``SetOfVCFFiles`` must be provided.

        The operation generates a base quality score recalibration table.

    knownSites : SetOfVCFFiles
        Set containing known-variant VCF files used by
        ``BaseRecalibrator``.

        This parameter is required when ``baseRecalibrator`` is enabled.

        If the set contains multiple VCF files, one is selected using
        ``vcfIndex``.

    vcfIndex : int
        Zero-based index of the ``VCFFile`` selected from ``knownSites``.

        The associated wizard can be used to select the desired VCF from
        the input set.

        The index must correspond to an existing element in the
        ``SetOfVCFFiles``.

    applyBQSR : bool
        If True, execute GATK ``ApplyBQSR``.

        This operation applies the recalibration table generated by
        ``BaseRecalibrator`` and produces a recalibrated BAM.

        ``BaseRecalibrator`` must also be enabled.


    ---------------------------------------------------------------------
    Output
    ---------------------------------------------------------------------

    outputAlignment : AlignmentFile
        Final processed BAM alignment.

        The output object is created by cloning the input
        ``AlignmentFile`` and updating the BAM and BAM index paths. This
        preserves the alignment metadata, including the associated
        reference genome information.

        The final BAM depends on the selected operations:

        - If ``ApplyBQSR`` is enabled, the recalibrated BAM is returned.
        - Otherwise, if ``SplitNCigarReads`` is enabled, the split BAM is
          returned.
        - Otherwise, the original input BAM is used.

        The final BAM is indexed with samtools and the resulting ``.bai``
        file is stored in the output ``AlignmentFile``.

        When supported by the ``AlignmentFile`` object, the output is also
        marked as indexed and sorted.

        The executed GATK commands are stored in the output alignment when
        command metadata are supported.


    ---------------------------------------------------------------------
    Workflow
    ---------------------------------------------------------------------

    The protocol performs the following steps:

    1. Retrieve the reference FASTA from the input ``AlignmentFile``.

    2. Check the reference FASTA and create its ``.fai`` index and
       sequence dictionary when necessary.

    3. If ``BaseRecalibrator`` is enabled, retrieve the selected known-sites
       VCF and ensure that a compatible VCF index is available.

    4. Execute ``SplitNCigarReads`` when selected.

    5. Execute ``BaseRecalibrator`` when selected and generate the
       recalibration table.

    6. Execute ``ApplyBQSR`` when selected using the generated
       recalibration table.

    7. Select the final BAM according to the operations that were executed.

    8. Index the final BAM using samtools.

    9. Create the output ``AlignmentFile`` while preserving the metadata
       associated with the input alignment.


    ---------------------------------------------------------------------
    Validation
    ---------------------------------------------------------------------

    Before execution, the protocol verifies that:

    - An input ``AlignmentFile`` has been provided.
    - The input BAM exists and is not empty.
    - At least one GATK operation has been selected.
    - ``ApplyBQSR`` is not selected without ``BaseRecalibrator``.
    - The input alignment contains a reference FASTA.
    - The reference FASTA exists.
    - A non-empty ``SetOfVCFFiles`` is provided when
      ``BaseRecalibrator`` is enabled.
    - The selected VCF index is valid.
    - The selected known-sites VCF exists.


    ---------------------------------------------------------------------
    Intermediate files
    ---------------------------------------------------------------------

    Depending on the selected operations, the protocol can generate:

    split_n_cigar_reads.bam
        BAM generated by ``SplitNCigarReads``.

    recalibration.table
        Base quality score recalibration table generated by
        ``BaseRecalibrator``.

    bqsr.bam
        BAM generated by ``ApplyBQSR``.

    gatk_commands.txt
        Internal record containing the GATK commands executed by the
        protocol.


    ---------------------------------------------------------------------
    Requirements
    ---------------------------------------------------------------------

    The following programs must be available through the RNA-seq
    environment configured by the Scipion-Chem plugin:

    - GATK
    - samtools


    ---------------------------------------------------------------------
    Notes
    ---------------------------------------------------------------------

    - This protocol is intended for processing RNA-seq BAM alignments.

    - ``SplitNCigarReads`` is specifically relevant for spliced RNA-seq
      alignments containing ``N`` CIGAR operators.

    - ``BaseRecalibrator`` requires a known-sites VCF.

    - Known-sites VCFs are provided as a ``SetOfVCFFiles``.

    - Only one VCF from the input ``SetOfVCFFiles`` is used in each
      protocol execution.

    - Existing ``.idx``, ``.tbi`` and ``.csi`` VCF indexes are accepted.

    - Missing FASTA indexes, sequence dictionaries and VCF feature indexes
      are generated automatically when required.

    - ``ApplyBQSR`` requires ``BaseRecalibrator`` to be enabled in the
      same protocol execution.

    - The final BAM is always indexed with samtools.

    - The output ``AlignmentFile`` preserves the metadata of the input
      alignment.

    - Mutect2 is intentionally not included in this protocol because
      variant calling produces VCF output rather than another
      ``AlignmentFile``.
    """

    _label = 'GATK processing'

    GATK_COMMAND = 'gatk {}'

    # -------------------------------------------------------
    # Parameters
    # -------------------------------------------------------

    def _defineParams(self, form):
        form.addSection(label='Input')

        form.addParam(
            'inputAlignment',
            PointerParam,
            pointerClass='AlignmentFile',
            label='Input alignment: ',
            help=(
                'Input BAM represented as an AlignmentFile object. '
                'The reference FASTA associated with the alignment is '
                'obtained automatically from this object.'
            )
        )

        form.addSection(label='GATK operations')

        form.addParam(
            'splitNCigarReads',
            BooleanParam,
            default=True,
            label='Split reads with N in CIGAR: ',
            help=(
                'Run GATK SplitNCigarReads. RNA-seq aligners use the N '
                'CIGAR operator for reads spanning splice junctions. '
                'This operation splits those reads into exon-like segments '
                'and prepares the BAM for downstream GATK processing.'
            )
        )

        form.addParam(
            'baseRecalibrator',
            BooleanParam,
            default=True,
            label='Base recalibrator: ',
            help=(
                'Run GATK BaseRecalibrator. This operation analyses base '
                'quality scores and known variant sites to build a '
                'recalibration model. It produces a recalibration table '
                'that can later be applied with ApplyBQSR.'
            )
        )

        form.addParam(
            'knownSites',
            PointerParam,
            pointerClass='SetOfVCFFiles',
            label='Known-sites VCFs: ',
            condition='baseRecalibrator',
            help=(
                'Set of VCF files containing known variants, such as dbSNP. '
                'If the set contains several VCF files, select the one to '
                'use with the Known-sites VCF parameter.'
            )
        )

        form.addParam(
            'vcfIndex',
            IntParam,
            default=0,
            label='Known-sites VCF: ',
            condition='baseRecalibrator',
            help=(
                'VCFFile selected from the input SetOfVCFFiles. '
                'Use the associated wizard to select the VCF.'
            )
        )

        form.addParam(
            'applyBQSR',
            BooleanParam,
            default=True,
            label='Apply base quality score recalibration (ApplyBQSR): ',
            help=(
                'Run GATK ApplyBQSR. This operation applies the recalibration '
                'table generated by BaseRecalibrator to the BAM and produces '
                'a recalibrated BAM file.'
            )
        )

        form.addParallelSection(
            threads=4,
            mpi=1
        )

    # -------------------------------------------------------
    # Steps
    # -------------------------------------------------------

    def _insertAllSteps(self):
        self._insertFunctionStep(self.prepareReferenceStep)

        if self.splitNCigarReads.get():
            self._insertFunctionStep(self.splitNCigarReadsStep)

        if self.baseRecalibrator.get():
            self._insertFunctionStep(self.baseRecalibratorStep)

        if self.applyBQSR.get():
            self._insertFunctionStep(self.applyBQSRStep)

        self._insertFunctionStep(self.indexFinalBamStep)
        self._insertFunctionStep(self.createOutputStep)

    # -------------------------------------------------------
    # Reference preparation
    # -------------------------------------------------------

    def prepareReferenceStep(self):
        alignment = self.inputAlignment.get()
        referenceFasta = self._getReferenceFasta(alignment)

        if not referenceFasta:
            raise RuntimeError(
                'GATK requires a reference FASTA stored in the '
                'input AlignmentFile.'
            )

        if not os.path.isfile(referenceFasta):
            raise RuntimeError(
                'Reference FASTA does not exist: {}'.format(referenceFasta)
            )

        self._ensureFastaIndex(referenceFasta)
        self._ensureSequenceDictionary(referenceFasta)

        if self.baseRecalibrator.get():
            knownSites = self._getKnownSitesFile()

            if not os.path.isfile(knownSites):
                raise RuntimeError(
                    'Known-sites VCF does not exist: {}'.format(
                        knownSites
                    )
                )

            self._ensureFeatureIndex(knownSites)

    # -------------------------------------------------------
    # GATK operations
    # -------------------------------------------------------

    def splitNCigarReadsStep(self):
        alignment = self.inputAlignment.get()
        inputBam = alignment.getFileName()
        referenceFasta = self._getReferenceFasta(alignment)
        outputBam = self._getSplitBam()

        self._validateBamFile(inputBam)

        args = (
            'SplitNCigarReads '
            '-R {reference} '
            '-I {inputBam} '
            '-O {outputBam}'
        ).format(
            reference=self._quote(referenceFasta),
            inputBam=self._quote(inputBam),
            outputBam=self._quote(outputBam)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        self._validateBamFile(outputBam)
        self._appendCommand(self.GATK_COMMAND.format(args))

    def baseRecalibratorStep(self):
        alignment = self.inputAlignment.get()
        inputBam = self._getInputAfterSplit()
        referenceFasta = self._getReferenceFasta(alignment)
        knownSites = self._getKnownSitesFile()
        recalTable = self._getRecalibrationTable()

        self._validateBamFile(inputBam)

        args = (
            'BaseRecalibrator '
            '-R {reference} '
            '-I {inputBam} '
            '--known-sites {knownSites} '
            '-O {recalTable}'
        ).format(
            reference=self._quote(referenceFasta),
            inputBam=self._quote(inputBam),
            knownSites=self._quote(knownSites),
            recalTable=self._quote(recalTable)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        if not os.path.isfile(recalTable):
            raise RuntimeError(
                'BaseRecalibrator did not create the recalibration table: {}'
                .format(recalTable)
            )

        self._appendCommand(self.GATK_COMMAND.format(args))

    def applyBQSRStep(self):
        alignment = self.inputAlignment.get()
        inputBam = self._getInputAfterSplit()
        referenceFasta = self._getReferenceFasta(alignment)
        recalTable = self._getRecalibrationTable()
        outputBam = self._getBqsrBam()

        self._validateBamFile(inputBam)

        if not os.path.isfile(recalTable):
            raise RuntimeError(
                'ApplyBQSR requires a recalibration table generated by '
                'BaseRecalibrator.'
            )

        args = (
            'ApplyBQSR '
            '-R {reference} '
            '-I {inputBam} '
            '--bqsr-recal-file {recalTable} '
            '-O {outputBam}'
        ).format(
            reference=self._quote(referenceFasta),
            inputBam=self._quote(inputBam),
            recalTable=self._quote(recalTable),
            outputBam=self._quote(outputBam)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        self._validateBamFile(outputBam)
        self._appendCommand(self.GATK_COMMAND.format(args))

    # -------------------------------------------------------
    # Final BAM
    # -------------------------------------------------------

    def indexFinalBamStep(self):
        finalBam = self._getFinalBam()

        self._validateBamFile(finalBam)

        Plugin.runCondaCommand(
            self,
            'index -@ {} {}'.format(
                self.numberOfThreads.get(),
                self._quote(finalBam)
            ),
            RNASEQ_DIC,
            'samtools'
        )

        baiFile = finalBam + '.bai'

        if not os.path.isfile(baiFile):
            raise RuntimeError(
                'BAM index was not created: {}'.format(baiFile)
            )

    def createOutputStep(self):
        inputAlignment = self.inputAlignment.get()

        finalBam = self._getFinalBam()
        finalBai = finalBam + '.bai'

        outputAlignment = inputAlignment.clone()
        outputAlignment.setFileName(finalBam)
        outputAlignment.setIndexFile(finalBai)
        outputAlignment.setIsIndexed(True)

        if hasattr(outputAlignment, 'setIsSorted'):
            outputAlignment.setIsSorted(True)

        if hasattr(outputAlignment, 'setCommand'):
            outputAlignment.setCommand(
                self._readCommandHistory()
            )

        self._defineOutputs(
            outputAlignment=outputAlignment
        )

        self._defineSourceRelation(
            self.inputAlignment,
            outputAlignment
        )

        if self.baseRecalibrator.get():
            self._defineSourceRelation(
                self.knownSites,
                outputAlignment
            )

    # -------------------------------------------------------
    # BAM flow
    # -------------------------------------------------------

    def _getInputAfterSplit(self):
        """Return the BAM produced by SplitNCigarReads, if enabled."""

        if self.splitNCigarReads.get():
            return self._getSplitBam()

        return self.inputAlignment.get().getFileName()

    def _getFinalBam(self):
        if self.applyBQSR.get():
            return self._getBqsrBam()

        if self.splitNCigarReads.get():
            return self._getSplitBam()

        return self.inputAlignment.get().getFileName()

    # -------------------------------------------------------
    # VCF selection
    # -------------------------------------------------------

    def _getSelectedVCF(self):
        """Return the VCFFile selected from the input SetOfVCFFiles."""

        vcfSet = self.knownSites.get()

        if vcfSet is None:
            raise RuntimeError(
                'No SetOfVCFFiles selected.'
            )

        if vcfSet.getSize() == 0:
            raise RuntimeError(
                'The selected SetOfVCFFiles is empty.'
            )

        index = self.vcfIndex.get()

        if index < 0 or index >= vcfSet.getSize():
            raise RuntimeError(
                'VCF index {} is out of range for a SetOfVCFFiles '
                'containing {} VCF(s).'.format(
                    index,
                    vcfSet.getSize()
                )
            )

        for currentIndex, vcfFile in enumerate(vcfSet):
            if currentIndex == index:
                return vcfFile.clone()

        raise RuntimeError(
            'The selected VCF could not be retrieved.'
        )

    def _getKnownSitesFile(self):
        """Return the path of the selected known-sites VCF."""

        vcfObject = self._getSelectedVCF()

        if not vcfObject:
            raise RuntimeError(
                'No known-sites VCF was selected.'
            )

        vcfFile = vcfObject.getFileName()

        if not vcfFile:
            raise RuntimeError(
                'The selected VCFFile does not contain a VCF path.'
            )

        return vcfFile

    # -------------------------------------------------------
    # Paths
    # -------------------------------------------------------

    def _getSplitBam(self):
        return self._getExtraPath(
            'split_n_cigar_reads.bam'
        )

    def _getBqsrBam(self):
        return self._getExtraPath(
            'bqsr.bam'
        )

    def _getRecalibrationTable(self):
        return self._getExtraPath(
            'recalibration.table'
        )

    def _getCommandFile(self):
        return self._getExtraPath(
            'gatk_commands.txt'
        )

    # -------------------------------------------------------
    # Command history
    # -------------------------------------------------------

    def _appendCommand(self, command):
        with open(self._getCommandFile(), 'a') as outputFile:
            outputFile.write(command + '\n')

    def _readCommandHistory(self):
        commandFile = self._getCommandFile()

        if not os.path.isfile(commandFile):
            return ''

        with open(commandFile) as inputFile:
            commands = [
                line.strip()
                for line in inputFile
                if line.strip()
            ]

        return ' && '.join(commands)

    # -------------------------------------------------------
    # Reference helpers
    # -------------------------------------------------------

    def _ensureFastaIndex(self, referenceFasta):
        fastaIndex = referenceFasta + '.fai'

        if os.path.isfile(fastaIndex):
            return

        Plugin.runCondaCommand(
            self,
            'faidx {}'.format(
                self._quote(referenceFasta)
            ),
            RNASEQ_DIC,
            'samtools'
        )

        if not os.path.isfile(fastaIndex):
            raise RuntimeError(
                'Reference FASTA index was not created: {}'.format(
                    fastaIndex
                )
            )

    def _ensureSequenceDictionary(self, referenceFasta):
        dictionaryFile = self._getSequenceDictionaryPath(
            referenceFasta
        )

        if os.path.isfile(dictionaryFile):
            return

        args = (
            'CreateSequenceDictionary '
            '-R {reference} '
            '-O {dictionary}'
        ).format(
            reference=self._quote(referenceFasta),
            dictionary=self._quote(dictionaryFile)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        if not os.path.isfile(dictionaryFile):
            raise RuntimeError(
                'Reference sequence dictionary was not created: {}'
                .format(dictionaryFile)
            )

    def _ensureFeatureIndex(self, featureFile):
        possibleIndexes = [
            featureFile + '.idx',
            featureFile + '.tbi',
            featureFile + '.csi'
        ]

        if any(
            os.path.isfile(indexFile)
            for indexFile in possibleIndexes
        ):
            return

        args = 'IndexFeatureFile -I {}'.format(
            self._quote(featureFile)
        )

        Plugin.runCondaCommand(
            self,
            args,
            RNASEQ_DIC,
            'gatk'
        )

        if not any(
            os.path.isfile(indexFile)
            for indexFile in possibleIndexes
        ):
            raise RuntimeError(
                'Known-sites VCF index was not created for: {}'
                .format(featureFile)
            )

    # -------------------------------------------------------
    # Alignment metadata
    # -------------------------------------------------------

    @staticmethod
    def _getReferenceFasta(alignment):
        if hasattr(alignment, 'getReferenceFasta'):
            return alignment.getReferenceFasta()

        return None

    @staticmethod
    def _getSequenceDictionaryPath(referenceFasta):
        root, extension = os.path.splitext(
            referenceFasta
        )

        if extension.lower() in (
            '.fa',
            '.fasta',
            '.fna'
        ):
            return root + '.dict'

        return referenceFasta + '.dict'

    # -------------------------------------------------------
    # Validation helpers
    # -------------------------------------------------------

    @staticmethod
    def _validateBamFile(bamFile):
        if not bamFile:
            raise RuntimeError(
                'The BAM path is empty.'
            )

        if not os.path.isfile(bamFile):
            raise RuntimeError(
                'BAM file does not exist: {}'.format(
                    bamFile
                )
            )

        if os.path.getsize(bamFile) == 0:
            raise RuntimeError(
                'BAM file is empty: {}'.format(
                    bamFile
                )
            )

    @staticmethod
    def _quote(value):
        return shlex.quote(str(value))

    def _validate(self):
        errors = []

        alignment = self.inputAlignment.get()

        if alignment is None:
            errors.append(
                'An input AlignmentFile object is required.'
            )
            return errors

        bamFile = alignment.getFileName()

        if not bamFile:
            errors.append(
                'The input AlignmentFile does not contain a BAM path.'
            )

        elif not os.path.isfile(bamFile):
            errors.append(
                'The input BAM file does not exist: {}'.format(
                    bamFile
                )
            )

        elif os.path.getsize(bamFile) == 0:
            errors.append(
                'The input BAM file is empty: {}'.format(
                    bamFile
                )
            )

        if not (
            self.splitNCigarReads.get()
            or self.baseRecalibrator.get()
            or self.applyBQSR.get()
        ):
            errors.append(
                'Select at least one GATK operation.'
            )

        if (
            self.applyBQSR.get()
            and not self.baseRecalibrator.get()
        ):
            errors.append(
                'ApplyBQSR requires BaseRecalibrator to be selected.'
            )

        referenceFasta = self._getReferenceFasta(
            alignment
        )

        if not referenceFasta:
            errors.append(
                'The input AlignmentFile does not contain a reference FASTA.'
            )

        elif not os.path.isfile(referenceFasta):
            errors.append(
                'The reference FASTA does not exist: {}'
                .format(referenceFasta)
            )

        if self.baseRecalibrator.get():
            vcfSet = self.knownSites.get()

            if vcfSet is None:
                errors.append(
                    'BaseRecalibrator requires a SetOfVCFFiles '
                    'containing known variants.'
                )

            elif vcfSet.getSize() == 0:
                errors.append(
                    'The selected SetOfVCFFiles is empty.'
                )

            else:
                index = self.vcfIndex.get()

                if (
                    index < 0
                    or index >= vcfSet.getSize()
                ):
                    errors.append(
                        'VCF index {} is out of range for a '
                        'SetOfVCFFiles containing {} VCF(s).'
                        .format(
                            index,
                            vcfSet.getSize()
                        )
                    )

                else:
                    try:
                        knownSites = self._getKnownSitesFile()

                        if not knownSites:
                            errors.append(
                                'The selected VCFFile does not '
                                'contain a VCF path.'
                            )

                        elif not os.path.isfile(knownSites):
                            errors.append(
                                'The known-sites VCF does not exist: {}'
                                .format(knownSites)
                            )

                    except RuntimeError as error:
                        errors.append(str(error))

        return errors

    # -------------------------------------------------------
    # Summary and methods
    # -------------------------------------------------------

    def _getSelectedOperationNames(self):
        operations = []

        if self.splitNCigarReads.get():
            operations.append(
                'SplitNCigarReads'
            )

        if self.baseRecalibrator.get():
            operations.append(
                'BaseRecalibrator'
            )

        if self.applyBQSR.get():
            operations.append(
                'ApplyBQSR'
            )

        return operations

    @staticmethod
    def _formatVCFSummary(vcfFile):
        scientificName = ''
        assembly = ''
        source = ''

        if hasattr(vcfFile, 'getScientificName'):
            scientificName = (
                vcfFile.getScientificName() or ''
            )

        if hasattr(vcfFile, 'getAssembly'):
            assembly = (
                vcfFile.getAssembly() or ''
            )

        if hasattr(vcfFile, 'getSource'):
            source = (
                vcfFile.getSource() or ''
            )

        values = [
            value
            for value in (
                scientificName,
                assembly,
                source
            )
            if value
        ]

        if values:
            return ' - '.join(values)

        return os.path.basename(
            vcfFile.getFileName()
        )

    def _getAvailableVCFsSummary(self):
        summary = []

        if not self.baseRecalibrator.get():
            return summary

        vcfSet = self.knownSites.get()

        if vcfSet is None:
            return summary

        if vcfSet.getSize() == 0:
            return summary

        summary.append(
            'Available known-sites VCFs:'
        )

        selectedIndex = self.vcfIndex.get()

        for index, vcfFile in enumerate(vcfSet):
            marker = (
                '*'
                if index == selectedIndex
                else ' '
            )

            summary.append(
                '{} {} -> {}'.format(
                    marker,
                    index,
                    self._formatVCFSummary(vcfFile)
                )
            )

        summary.extend([
            '',
            "Use the wizard next to 'Known-sites VCF' "
            "to select the VCF.",
            ''
        ])

        return summary

    def _summary(self):
        operations = ' -> '.join(
            self._getSelectedOperationNames()
        )

        summary = [
            'Selected GATK operations: {}'.format(
                operations
            )
        ]

        summary.extend(
            self._getAvailableVCFsSummary()
        )

        if not hasattr(self, 'outputAlignment'):
            return summary

        summary.append(
            'Output BAM: {}'.format(
                self.outputAlignment.getFileName()
            )
        )

        if self.baseRecalibrator.get():
            summary.append(
                'Known-sites VCF: {}'.format(
                    self._getKnownSitesFile()
                )
            )

            summary.append(
                'Recalibration table: {}'.format(
                    self._getRecalibrationTable()
                )
            )

        return summary

    def _methods(self):
        if not hasattr(self, 'outputAlignment'):
            return []

        operations = ' followed by '.join(
            self._getSelectedOperationNames()
        )

        return [
            'The input RNA-seq BAM alignment was processed with GATK using '
            '{}. The resulting BAM file was indexed with samtools.'
            .format(operations)
        ]