from .viewer_protocol_dali import ProtBioinformaticsDaliViewer
from .viewer_protocol_ZL_predict import ProtBioinformaticsZLPredictViewer
from .viewer_protocol_raptorX import ProtBioinformaticsRaptorXViewer
from .viewers_data import BioinformaticsDataViewer