name: Build & test plugin

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup enviroment
        uses: scipion-chem/.github/.github/composites/install-scipion@main

      - name: Install plugin from pull request
        working-directory: ${{ github.workspace }}
        run: ../scipion/scipion3 installp -p . --devel

      - name: Run tests
        working-directory: ${{ github.workspace }}/${{ vars.FOLDER_WITH_VERSION }}
        run: |
          ../../scipion/scipion3 tests --grep pwchem
          pip install --user scipion-testrunner
          scipion_testrunner ${{ github.workspace }}/../scipion/scipion3 ${{ vars.FOLDER_WITH_VERSION }} --noGpu --testData=testData.json
